### ISSUE TITLE
`error creating container storage: the container name "etcdctl" is already in use` on bootstrap

### ISSUE THREAD

**Issue by Hyun-June-Choi** [okd-project/okd#1260] opened 2022-06-13 03:51 UTC
**Describe the bug**

Describe the bug : Bootstrap failed to complete
[root@api ~]# ./openshift-install --dir=./c0 wait-for bootstrap-complete --log-level=debug
DEBUG OpenShift Installer 4.10.0-0.okd-2022-05-28-062148 
DEBUG Built from commit 25f497505abeaf6b8563bd97bb21037159cb61ad 
INFO Waiting up to 20m0s (until 10:23AM) for the Kubernetes API at https://api.c0.lbcore.local:6443... 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
DEBUG Still waiting for the Kubernetes API: Get "https://api.c0.lbcore.local:6443/version": EOF 
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get "https://api.c0.lbcore.local:6443/apis/config.openshift.io/v1/clusteroperators": EOF 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
ERROR Bootstrap failed to complete: Get "https://api.c0.lbcore.local:6443/version": EOF 
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane. 
FATAL Bootstrap failed to complete                 

**Version**

4.10.0-0.okd-2022-05-28-062148 
fedora-coreos-35.20220327.3.0-vmware.x86_64.ova from "openshift-install coreos print-stream-json"

**How reproducible**

100%

**Log bundle**

Log bundle : 
[log-bundle-20220613102550.tar.gz](https://github.com/openshift/okd/files/8887756/log-bundle-20220613102550.tar.gz)

[core@master0 ~]$ ./installer-masters-gather.sh c0-2wbtl 192.168.50.110 192.168.50.111 192.168.50.112
Gathering master systemd summary ...
Gathering master failed systemd unit status ...
Gathering master journals ...
Gathering master networking ...
Gathering master containers ...
./installer-masters-gather.sh: line 42: crictl: command not found
Gathering master rpm-ostree info ...
Waiting for logs ...

**Comment by vrutkovs** [comment] 2022-06-13 06:42
```
Jun 13 02:57:42 bootstrap.c0.lbcore.local bootkube.sh[3952]: Error: error creating container storage: the container name "etcdctl" is already in use by "a58e24816d9a57935ca1049512e83169e0602918c269cc29c6fdfed6921028be". You have to remove that container to be able to reuse that name.: that name is already in use
Jun 13 02:57:42 bootstrap.c0.lbcore.local bootkube.sh[1690]: etcdctl failed. Retrying in 5 seconds...
```

We started seeing more of that in CI, seems to be an installer bug. Not quite sure why it happens - probably we should be holding off `bootkube` before pivot is complete?

**Comment by Hyun-June-Choi** [comment] 2022-06-13 08:21
Is it the same issue as this? https://github.com/openshift/okd/issues/1204
@fortinj66 Doesn't it happen in version 4.9?

**Comment by vrutkovs** [comment] 2022-06-13 08:24
Yeah, seems to be a dupe of #1204

**Comment by fortinj66** [comment] 2022-06-13 14:23
> Is it the same issue as this? #1204
> @fortinj66 Doesn't it happen in version 4.9?

I don't recall seeing it in 4.9 but I wasn't really looking then...

**Comment by fortinj66** [comment] 2022-06-13 14:26
> We started seeing more of that in CI, seems to be an installer bug. Not quite sure why it happens - probably we should be holding off `bootkube` before pivot is complete?

Hmmmmm, interesting point.  I wonder if the pods are being created prior to the pivot and end up in a bad state because of the pivot and thus fail because the storage has already been allocated

**Comment by fortinj66** [comment] 2022-06-13 14:33
https://github.com/openshift/installer/issues/5858

**Comment by Hyun-June-Choi** [comment] 2022-06-14 04:54
> 

Is the physical environment(machine specification) where 4.9, 4.10 are installed the same?

**Comment by QkiZMR** [comment] 2022-11-01 13:06
I have the same problem on 4.11. How to remove the container that blocks starting of etcdctl?

**Comment by vrutkovs** [comment] 2022-11-01 13:14
You can ssh on the machine and remove it using `crictl`

**Comment by yummypeng** [comment] 2022-12-08 09:47
> 

This doesn't work for me, every time i remove the existing etcdctl container, a new one is created immediately, and the error continues the same.

I am using 4.11.0-0.okd-2022-11-05-030711.

**Comment by avilte** [comment] 2022-12-08 22:37
I had the same error in the boostrap node with okd 4.10.

_Dec 08 21:24:41 bootstrap.okdtecno.bancocredicoop.coop bootkube.sh[145519]: Error: error creating container storage: the container name "cco-render" is already in use by "ffb4fe215188efe1dde69d6bcdc7e1cebc6c8b3f535dc83bd62d42f83e5c3423". You have to remove that container to be able to reuse that name.: that name is already in use_

 I'was able to solve:
1) ssh core@bootstrapnode //
2) sudo  podman ps -a //(look at container-ID with problem).  In my case says: fb4fe215188e
3) delete container-id (sudo podman rm fb4fe215188e) //

**Comment by yummypeng** [comment] 2022-12-09 02:46
@avilte  This also works for me, thanks 😆

**Comment by vrutkovs** [comment] 2023-01-27 14:45
Resolved in 4.11+ by https://github.com/openshift/installer/pull/6759

**Closed by vrutkovs** 2023-01-27 14:45 UTC

**Comment by ggvaro** [comment] 2023-03-31 09:56
I´m having this issue using 4.11.0-0.okd-2022-10-28-153352. Is there something else that can make it happen?

**Comment by peterroth** [comment] 2023-07-24 09:52
I ran into this issue on OKD 4.11.0-0.okd-2023-01-14-152430. Killing the etcdctl container brought success, the progress went further.
