### ISSUE TITLE
OKD Client `oc` does not run on Apple Silicon

### ISSUE THREAD

**Issue by cgruver** [okd-project/okd#1419] opened 2022-11-24 14:39 UTC
Apple MacBook Air M2
OKD version: `4.11.0-0.okd-2022-11-19-050030`
MacOS version: `13.0.1 (22A400)`

1. download [openshift-client-mac-arm64-4.11.0-0.okd-2022-11-19-050030.tar.gz](https://github.com/okd-project/okd/releases/download/4.11.0-0.okd-2022-11-19-050030/openshift-client-mac-arm64-4.11.0-0.okd-2022-11-19-050030.tar.gz)

1. Uncompress on an M2 MacBook

1. Run `oc`

1. Observe the error:

   ```bash
   “oc” is damaged and can’t be opened. You should move it to the Trash.
   ```

If you build the OpenShift client from source on the M2 platform, then it works.

**Comment by vrutkovs** [comment] 2022-11-28 10:18
Could anyone check if `oc` extracted from 4.12 nightlies work? If it is, then its a dupe of https://bugzilla.redhat.com/show_bug.cgi?id=2059125

**Comment by cgruver** [comment] 2022-11-28 12:03
@vrutkovs I suspect that you are correct.

This workaround fixes it for now:

```bash
codesign --force -s - $PATH_TO_OC/oc
```

**Comment by cgruver** [comment] 2022-11-28 12:16
@vrutkovs   It looks like it is still broken in 4.12 nightlies:

```bash
oc adm release extract --tools registry.ci.openshift.org/origin/release:4.12.0-0.okd-2022-11-28-091559
tar -xzf openshift-client-mac-arm64-4.12.0-0.okd-2022-11-28-091559.tar.gz
```

```bash
./oc version
zsh: killed     ./oc version
```

```bash
codesign --force -s - oc                                
oc: replacing existing signature
```

```bash
./oc version            
Client Version: 4.12.0-0.okd-2022-11-28-091559
Kustomize Version: v4.5.7
```

**Comment by JaimeMagiera** [comment] 2024-08-15 13:46
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

Please test with the OKD SCOS nightlies and file a new issue as needed.

Many thanks,

Jaime

**Closed by JaimeMagiera** 2024-08-15 13:46 UTC
