### ISSUE TITLE
wrong checksum in sha256sum.txt (or on files)

### ISSUE THREAD

**Issue by azzid** [okd-project/okd#1911] opened 2024-03-26 15:33 UTC
**Describe the bug**

shasum fails on openshift-*-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz

```
➜   oc adm release extract --tools quay.io/openshift/okd:4.15.0-0.okd-2024-03-10-010116
➜   ls
openshift-client-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz  release.txt
openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz sha256sum.txt
➜   shasum --algorithm 256 --check sha256sum.txt                                       
openshift-client-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz: FAILED
openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz: FAILED
release.txt: OK
shasum: WARNING: 2 computed checksums did NOT match
➜   grep mac-arm sha256sum.txt 
30c97343b963b9d0480f462418cb3199ab7dbd243859c1f177f12e4f337410e1  openshift-client-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz
40c898789413346d4cbce9e3ca34fdda4bb13fcae26573531d4eff7bf79bc291  openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz
➜   shasum --algorithm 256 *mac-arm*            
b5a27febe641736028a51e7ef75a1b22dde23d1b4aa5b0fde71230b936c5eeb7  openshift-client-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz
792faf3f01eace8f6a224a1e706f175f224cc3438a16d09259028e80b0afd17a  openshift-install-mac-arm64-4.15.0-0.okd-2024-03-10-010116.tar.gz
```

**Version**

4.15.0-0.okd-2024-03-10-010116

not been able to do the install yet, so not sure if UPI or IPI - attempting install on bare-metal though

**How reproducible**

100%

**Log bundle**

    $ oc adm must-gather
    error: Missing or incomplete configuration info.

**Comment by codespearhead** [comment] 2024-04-08 20:27
Duplicate of #1569 . Can you close this issue in favor of that one?

**Closed** 2024-04-08 20:48 UTC
