### ISSUE TITLE
okd 4.11 install on azure fails with os image override (fcos)

### ISSUE THREAD

**Issue by jleski** [okd-project/okd#1416] opened 2022-11-21 09:24 UTC
**Describe the bug**
Installation fails on Azure with OS image override setting.
Installer attempts to create terraform `azurerm_image` resource but fails because source blob `azurerm_storage_blob.rhcos_image` is Block type.

**Version**
OKD: 4.11.0-0.okd-2022-11-19-050030
Azure Public Cloud (Germany West Central)
FCOS fedora-coreos-36.20221030.3.0-azure.x86_64
IPI

**How reproducible**
100%

**Log bundle**
n/a - bootstrap node does not get created

Installer logs
```bash
$ ./openshift-install version
./openshift-install 4.11.0-0.okd-2022-11-19-050030
built from commit 0c4e73175c1aaa2140fb360ce8ff44a4b9dd669f
release image quay.io/openshift/okd@sha256:b2e925d0178130baa99ebdcdf9bfe124a1fa496cae955af5543652c2166def63
release architecture amd64

$ export OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE="https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20221030.3.0/x86_64/fedora-coreos-36.20221030.3.0-azure.x86_64.vhd.xz?sha256=ad735bdd450827c539b3339ab4ed37c697935d9ece44071cb918e1832ab56dbe"

$ ./openshift-install create cluster --dir cluster --log-level=debug
...
DEBUG azurerm_storage_blob.rhcos_image: Creating... 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [10s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [20s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [30s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [40s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [50s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m0s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m10s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m20s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m30s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m40s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Still creating... [1m40s elapsed] 
DEBUG azurerm_storage_blob.rhcos_image: Creation complete after 1m46s [id=https://clusterl9ky0.blob.core.windows.net/vhd/rhcosl9ky0.vhd] 
DEBUG azurerm_image.cluster: Creating...           
DEBUG azurerm_image.clustergen2: Creating...       
ERROR                                              
ERROR Error: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The source blob https://clusterl9ky0.blob.core.windows.net/vhd/rhcosl9ky0.vhd is not a page blob." Target="disks" 
ERROR                                              
ERROR   with azurerm_image.cluster,                
ERROR   on main.tf line 94, in resource "azurerm_image" "cluster": 
ERROR   94: resource "azurerm_image" "cluster" {   
ERROR                                              
ERROR                                              
ERROR Error: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The source blob https://clusterl9ky0.blob.core.windows.net/vhd/rhcosl9ky0.vhd is not a page blob." Target="disks" 
ERROR                                              
ERROR   with azurerm_image.clustergen2,            
ERROR   on main.tf line 106, in resource "azurerm_image" "clustergen2": 
ERROR  106: resource "azurerm_image" "clustergen2" { 
ERROR                                              
ERROR failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "vnet" stage: failed to create cluster: failed to apply Terraform: exit status 1 
```

Somehow this is being omitted:

https://github.com/openshift/installer/blob/0c4e73175c1aaa2140fb360ce8ff44a4b9dd669f/data/data/azure/vnet/main.tf#L89

```hcl
resource "azurerm_storage_blob" "rhcos_image" {
  name                   = "rhcos${random_string.storage_suffix.result}.vhd"
  storage_account_name   = azurerm_storage_account.cluster.name
  storage_container_name = azurerm_storage_container.vhd.name
  type                   = "Page"
  source_uri             = var.azure_image_url
  metadata               = map("source_uri", var.azure_image_url)
}
```

**Comment by vrutkovs** [comment] 2022-11-21 10:17
Dupe of #531

**Closed by vrutkovs** 2022-11-21 10:17 UTC
