### ISSUE TITLE
Cluster is updating to 4.12.0-0.okd-2023-02-04-212953 Console-operator in Degraded state

### ISSUE THREAD

**Issue by madpearl** [okd-project/okd#1498] opened 2023-02-07 14:43 UTC
**Describe the bug**
Message
    ConsoleNotificationSyncDegraded: rpc error: code = Unknown desc = malformed header: missing HTTP content-type

**Version**
4.12.0-0.okd-2023-02-04-212953

**Log bundle**

[event-console-operator.log](https://github.com/okd-project/okd/files/10676204/event-console-operator.log)
[must-gather-local.tar.gz](https://github.com/okd-project/okd/files/10677267/must-gather-local.tar.gz)

**Comment by JaimeMagiera** [comment] 2023-02-07 15:33
Hi. What you've provided is not a log bundle. Please see...
https://docs.okd.io/4.11/support/gathering-cluster-data.html

**Comment by madpearl** [comment] 2023-02-07 16:22
I've added file must-gather-local.tar.gz , which is an output from `oc adm must-gather`

**Comment by vrutkovs** [comment] 2023-02-07 16:57
Dupe of  #1482

**Closed by vrutkovs** 2023-02-07 16:57 UTC
