### ISSUE TITLE
Huge master nodes cpu/memory consumption 

### ISSUE THREAD

**Issue by dkoci** [okd-project/okd#1456] opened 2022-12-29 17:51 UTC
After upgrading to 4.11 we noticed some issue with master nodes. All of sudden master nodes start using a lot of cpu/memory which causes nodes crash.
Pods stuck in ContainerCreating and Terminating status.
Please see the attached gather logs.
[must-gather.tar.gz](https://github.com/okd-project/okd/files/10320808/must-gather.tar.gz)

**Comment by nate-duke** [comment] 2022-12-29 19:20
Hi again @dkoci! Have you looked over https://github.com/okd-project/okd/issues/1310?

It's a pretty epic read but there's some graphs and narrative in there and lots of folks have chimed in as well. Worth going through some of that to see if it matches your observations.

**Comment by dkoci** [comment] 2022-12-29 22:38
Thanks for sharing. It looks the same as our issue. But There is no solution on the horizon.

**Comment by vrutkovs** [comment] 2022-12-30 08:22
Dupe of #1310

**Closed by vrutkovs** 2022-12-30 08:22 UTC
