### ISSUE TITLE
Release not accepted

### ISSUE THREAD

**Issue by dkoci** [okd-project/okd#1729] opened 2023-09-08 17:55 UTC
Hi.
I would like to update OKD from version 4.12 (4.12.0-0.okd-2023-04-16-041331) to version 4.13. The only available version in stable-4.13 chanel is 4.13.0-0.okd-2023-05-22-052007. Why there are no newer versions?
I chose 4.13.0-0.okd-2023-05-22-052007. I clicked update, but got an error "Release not accepted".
`Retrieving payload failed version="4.13.0-0.okd-2023-05-22-052007" image="registry.ci.openshift.org/origin/release@sha256:16b7227d0c0de198d65c4478617e402d7f67ffc0dee312110a9d4c85877e5e4d" failure=The update cannot be verified: unable to verify sha256:16b7227d0c0de198d65c4478617e402d7f67ffc0dee312110a9d4c85877e5e4d against keyrings: verifier-public-key-ci`

**Comment by vrutkovs** [comment] 2023-09-08 18:33
Dupe of https://github.com/okd-project/okd/issues/1618

**Closed by vrutkovs** 2023-09-08 18:33 UTC

**Comment by dkoci** [comment] 2023-09-08 18:37
Just found the answer here: https://github.com/okd-project/okd/discussions/1706.
I did --force upgrade.
