### ISSUE TITLE
SSL certificate renewal failed in OKD 3.11

### ISSUE THREAD

**Issue by tj77777** [okd-project/okd#1336] opened 2022-09-09 07:54 UTC
### Discussed in https://github.com/okd-project/okd/discussions/1335

<div type='discussions-op-text'>

<sup>Originally posted by **tj77777** September  9, 2022</sup>
Hi  All,

**OKD version - 3.11**

I have faced an issue when trying to update the SSL certificate in OKD. Even though the certificate renewal was successful nodes did not come to the ready state. after checking the errors in kubelet log, we can observe and error "cni plugin not available". pods are not starting because it's stuck at the container starting state. 

**Please find the commands below that I used to execute when updating the SSL certificate**  

ansible-playbook -i  inventory playbooks/openshift-master/redeploy-openshift-ca.yml                    
ansible-playbook -i  inventory playbooks/redeploy-certificates.yml -e openshift_redeploy_openshift_ca=true

**The below file was not available in the worker/master nodes that have not been in a ready state** 
/etc/cni/net.d/80-openshift-network.conf

</div>

**Comment by YasithaLearn** [comment] 2022-09-09 08:00
I have faced same issue. Appreciate can someone help me regarding this please ?

**Comment by dinush-rh** [comment] 2022-09-09 08:00
Hi,
I had the similar issue. After executing 'redeploy_certificate' , my master and worker nodes are in 'NotReady' state.
Appreciate if someone can help.

**Comment by vrutkovs** [comment] 2022-09-09 09:12
Dupe of https://github.com/okd-project/okd/discussions/1335

This repo is for OKD 4 bugs though, as OKD 3 is no longer being developed

**Closed by vrutkovs** 2022-09-09 09:12 UTC
