### ISSUE TITLE
Observe menu after upgrade to version 4.14.0-0.okd-2024-01-06-084517 is not available. Dynamic monitoring-plugin cannot loaded.

### ISSUE THREAD

**Issue by madpearl** [okd-project/okd#1855] opened 2024-01-12 13:43 UTC
**Describe the bug**
After upgrade to version 4.14.0-0.okd-2024-01-06-084517 the Dynamic Plugin status of **monitoring-plugin** is degraded with error 
```
Failed
Failed to get a valid plugin manifest from /api/plugins/monitoring-plugin/
SyntaxError: Unexpected end of JSON input
```
at this time the Console Observe menu is not available!

![image](https://github.com/okd-project/okd/assets/51110490/4c52bf25-9870-4da3-bfeb-f0d7c26faa1a)

The plugin-manifest.json configuration is available from the console pods.
Curl request to plugin-manifest.json:

```
sh-4.4$ curl -k https://monitoring-plugin.openshift-monitoring.svc.cluster.local:9443/plugin-manifest.json
{
  "name": "monitoring-plugin",
  "version": "1.0.0",
  "displayName": "OpenShift console monitoring plugin",
  "description": "This plugin adds the monitoring UI to the OpenShift web console",
  "dependencies": {
    "@console/pluginAPI": "*"
  },
  "extensions": [
    {
      "type": "console.page/route",
      "properties": {
        "exact": true,
        "path": "/monitoring",
        "component": {
          "$codeRef": "MonitoringUI"
        }
      }
    },
    {
      "type": "console.page/route",
      "properties": {
        "exact": false,
        "path": "/monitoring/(alertrules|alerts|dashboards|graph|query-browser|silences|targets)/",
        "component": {
          "$codeRef": "MonitoringUI"
        }
      }
    },
    {
      "type": "console.navigation/href",
      "flags": {
        "required": [
          "PROMETHEUS",
          "MONITORING",
          "CAN_GET_NS"
        ]
      },
      "properties": {
        "id": "alerting",
        "name": "%public~Alerting%",
        "href": "/monitoring/alerts",
        "perspective": "admin",
        "section": "observe",
        "startsWith": [
          "monitoring/alertrules",
          "monitoring/silences"
        ]
      }
    },
    {
      "type": "console.navigation/href",
      "flags": {
        "required": [
          "PROMETHEUS",
          "MONITORING",
          "CAN_GET_NS"
        ]
      },
      "properties": {
        "id": "metrics",
        "name": "%public~Metrics%",
        "href": "/monitoring/query-browser",
        "perspective": "admin",
        "section": "observe",
        "insertAfter": "alerts"
      }
    },
    {
      "type": "console.navigation/href",
      "flags": {
        "required": [
          "PROMETHEUS",
          "MONITORING",
          "CAN_GET_NS"
        ]
      },
      "properties": {
        "id": "dashboards",
        "name": "%public~Dashboards%",
        "href": "/monitoring/dashboards",
        "perspective": "admin",
        "section": "observe",
        "insertAfter": "metrics"
      }
    },
    {
      "type": "console.navigation/href",
      "flags": {
        "required": [
          "PROMETHEUS",
          "MONITORING",
          "CAN_GET_NS"
        ]
      },
      "properties": {
        "id": "targets",
        "name": "%public~Targets%",
        "href": "/monitoring/targets",
        "perspective": "admin",
        "section": "observe",
        "insertAfter": "dashboards"
      }
    }
  ]
}sh-4.4$ 
```

**Version**
4.14.0-0.okd-2024-01-06-084517

**How reproducible**
I thing it is not reproducible, because on the other OKD cluster with the same version the problem not exist.

**Log bundle**

**Comment by vrutkovs** [comment] 2024-01-12 14:02
Dupe of https://github.com/okd-project/okd/issues/1852

**Closed by vrutkovs** 2024-01-12 14:02 UTC
