### ISSUE TITLE
update okd from 4.11 to 4.12 got "open /etc/containers/registries.conf: permission denied"

### ISSUE THREAD

**Issue by wuyexixi** [okd-project/okd#1851] opened 2024-01-09 11:15 UTC
**Describe the bug**

Node machine-config-daemon reports:

E0109 11:13:51.640347 2846196 writer.go:200] Marking Degraded due to: failed to update OS to quay.io/openshift/okd-content@sha256:53abd41811f53c940ac41dc8b9d5475813d9c96e20ce893c8664ba951044d6a3 : error running rpm-ostree rebase --experimental ostree-unverified-registry:quay.io/openshift/okd-content@sha256:53abd41811f53c940ac41dc8b9d5475813d9c96e20ce893c8664ba951044d6a3: error: remote error: loading registries configuration: loading registries configuration "/etc/containers/registries.conf": open /etc/containers/registries.conf: permission denied
: exit status 1

**Version**

4.11.0-0.okd-2022-12-02-145640 ->  Update to 4.12.0-0.okd-2023-04-16-041331

**How reproducible**

**Log bundle**

**Comment by vrutkovs** [comment] 2024-01-09 11:31
Dupe of https://github.com/okd-project/okd/discussions/1500#discussioncomment-5919291?

**Closed by vrutkovs** 2024-01-09 11:31 UTC
