### ISSUE TITLE
PVC capacity showing a negative value

### ISSUE THREAD

**Issue by schmts** [okd-project/okd#1880] opened 2024-02-09 12:54 UTC
Today I noticed all PVCs (excluding the image-registry) of both of our OKD clusters  showing a negative value for space available. 
In the list view of al PVCs the values of space being used is the same on every PVC which greatly exceeds its capacity. 

Just recently we've installed kubeturbo on both of those clusters so I'm thinking this might be a clue towards the weird behaviour.

**Comment by schmts** [comment] 2024-02-09 12:55
![slika](https://github.com/okd-project/okd/assets/99176060/d04ee623-4b19-433d-bc07-db30bbe82474)
![slika](https://github.com/okd-project/okd/assets/99176060/25ff07ab-23bd-4c5e-9b6e-bac2a8a33fb8)

**Comment by vrutkovs** [comment] 2024-02-09 15:45
Dupe of https://github.com/okd-project/okd/discussions/1274?

**Closed by vrutkovs** 2024-02-09 15:45 UTC
