### ISSUE TITLE
OKD >= 4.11 installs may fail on various AWS region due to AWS S3 policy change

### ISSUE THREAD

**Issue by apmlima** [okd-project/okd#1587] opened 2023-05-03 08:06 UTC
OKD 4.11 / 4.12 installation on AWS will report errors as shown below.
$ ./openshift-install create cluster --dir t9
...
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error creating S3 bucket ACL for t9-r5h2p-bootstrap: AccessControlListNotSupported: The bucket does not allow ACLs
level=error msg=	status code: 400, request id: YGX5Z64B70KEB5W4, host id: wnWfplUMk+SKTydGm66E47JP4F7BaKC7WTfgj5goCJAJoGFc+IpyBF0nw5aIQfeMGuQHTL0NM18=
level=error
level=error msg=  with aws_s3_bucket_acl.ignition,
level=error msg=  on main.tf line 62, in resource "aws_s3_bucket_acl" "ignition":
level=error msg=  62: resource "aws_s3_bucket_acl" ignition {
level=error
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "bootstrap" stage: failed to create cluster: failed to apply Terraform: exit status 1
level=error
level=error msg=Error: error creating S3 bucket ACL for t9-r5h2p-bootstrap: AccessControlListNotSupported: The bucket does not allow ACLs
level=error msg=	status code: 400, request id: YGX5Z64B70KEB5W4, host id: wnWfplUMk+SKTydGm66E47JP4F7BaKC7WTfgj5goCJAJoGFc+IpyBF0nw5aIQfeMGuQHTL0NM18=
level=error
level=error msg=  with aws_s3_bucket_acl.ignition,
level=error msg=  on main.tf line 62, in resource "aws_s3_bucket_acl" "ignition":
level=error msg=  62: resource "aws_s3_bucket_acl" ignition {

Seems to be described here https://access.redhat.com/solutions/7007136

Can you provide a fixed 4.11 stable version?

OKD 4.11 / 4/12 in AWS

**How reproducible**

**Comment by vrutkovs** [comment] 2023-05-03 08:35
Dupe of #1573

**Closed by vrutkovs** 2023-05-03 08:35 UTC
