### ISSUE TITLE
OKD 4.12.0-0.okd-2023-02-04-212953 IPI installation on Azure fails consistently

### ISSUE THREAD

**Issue by benemon** [okd-project/okd#1501] opened 2023-02-09 09:39 UTC
**Describe the bug**

Installing OKD 4.12 into Azure consistently fails with:

```
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "CVO Ignore": failed to fetch dependency of "Openshift Manifests": failed to generate asset "Image": stable/x86_64: No azure build found 
```

Previously with 4.11, I could work around this by uploading the FCOS image to a Storage Account, and setting the image override with:

```
export OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE=https://okdimages.blob.core.windows.net/vhd/fedora-coreos-37.vhd
```

This changes the error slightly, although the end result is the same:

```
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Bootstrap Ignition Config": failed to fetch dependency of "Worker Machines": failed to generate asset "Release": stable/x86_64: No azure build found 
```

**Version**

**How reproducible**

Always

**Log bundle**

[install-fail-no-override.log - no image override set](https://github.com/okd-project/okd/files/10695621/install-fail-no-override.log)
[install-fail-override.log - with image override set](https://github.com/okd-project/okd/files/10695622/install-fail-override.log)

**Comment by vrutkovs** [comment] 2023-02-09 09:43
Dupe of https://github.com/okd-project/okd/issues/13#issuecomment-564692550

**Closed by vrutkovs** 2023-02-09 09:43 UTC

**Comment by benemon** [comment] 2023-02-09 13:38
@vrutkovs given that the workarounds previously stipulated for this no longer work, is it the same issue?
